
engines:
    duplication:
        enabled: true
        config:
            languages:
                - php
        exclude_fingerprints:
    fixme:
        enabled: true
    phpmd:
        enabled: true


ratings:
    paths:
        - "**.php"

exclude_paths:
    - tests/