
language: php

git:
    depth: 5

php:
    - 7.1
    - 7.2

after_script:
    - php bin/tale-dev code-style:check
    - php bin/tale-dev coverage:report coverage.xml --php-version=7.1

install:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - php bin/tale-dev install

script:
    - ./vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

addons:
    code_climate:
        repo_token: df715e9a48f53882ebee8b80f47faa89814f01d0341c64989c74826f4588be93
