
language: php

git:
    depth: 5

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

after_script:
    - php bin/phug-dev code-style:check
    - vendor/bin/test-reporter --coverage-report coverage.xml

install:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - php bin/phug-dev install

script:
    - ./vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

notifications:
    slack: phug:nzXFnxhU14RWK2EQSDL0u08z

addons:
    code_climate:
        repo_token: 906b964cfdb65c53a734b2cb88e9b4cd32b0424f3404008e9bfde7cb675254a4
