
language: php

git:
    depth: 5

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

install:
    - php bin/phug-dev install

script:
    - php bin/phug-dev code-style:check

notifications:
    slack: phug:nzXFnxhU14RWK2EQSDL0u08z