
language: php

git:
    depth: 5

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

after_script:
    - vendor/bin/test-reporter --coverage-report coverage.xml

install:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - php bin/phug-dev install

script:
    - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml && php bin/phug-dev code-style:check

notifications:
    slack: phug:nzXFnxhU14RWK2EQSDL0u08z

addons:
    code_climate:
        repo_token: e6c2d122be93cd3065c503a130e4203e4359fc0a67ab0a72b971f4c94f617cd8
